# Generated by Django 5.2.3 on 2025-06-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='apply_link',
        ),
        migrations.RemoveField(
            model_name='career',
            name='description',
        ),
        migrations.AddField(
            model_name='career',
            name='no',
            field=models.PositiveIntegerField(default=1, unique=True),
        ),
        migrations.AddField(
            model_name='career',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='careers/'),
        ),
        migrations.AddField(
            model_name='career',
            name='status',
            field=models.CharField(default='Published', max_length=50),
        ),
        migrations.AddField(
            model_name='tender',
            name='no',
            field=models.CharField(default='TEMP_NO', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=50),
        ),
    ]
