# Generated by Django 5.2.3 on 2025-06-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_career_apply_link_remove_career_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnniversaryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='anniversary/')),
                ('alt_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Conclave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='events/')),
                ('source', models.CharField(blank=True, max_length=255)),
                ('link', models.URLField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inauguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='events/')),
                ('source', models.CharField(blank=True, max_length=255)),
                ('link', models.URLField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='events/')),
                ('source', models.CharField(blank=True, max_length=255)),
                ('link', models.URLField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
