# Generated by Django 5.2.3 on 2025-06-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_anniversaryimage_conclave_inauguration_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConclaveRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=100)),
                ('youtube_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ConclaveSpeaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='conclave/speakers/')),
            ],
        ),
        migrations.CreateModel(
            name='InaugurationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='inauguration/')),
                ('alt', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Conclave',
        ),
        migrations.DeleteModel(
            name='Inauguration',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='description',
            new_name='excerpt',
        ),
        migrations.RemoveField(
            model_name='anniversaryimage',
            name='alt_text',
        ),
        migrations.AddField(
            model_name='anniversaryimage',
            name='alt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='news/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='source',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
