# Generated by Django 5.2.3 on 2025-06-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_conclaverecording_conclavespeaker_inaugurationimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='type',
            field=models.CharField(default='news', max_length=100),
        ),
    ]
