# Generated by Django 5.2.3 on 2025-06-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_news_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('date', models.DateField()),
                ('pdf', models.FileField(upload_to='govt_orders/')),
            ],
        ),
    ]
