# Generated by Django 5.2.3 on 2025-06-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='project',
            field=models.CharField(max_length=255),
        ),
    ]
