# Generated by Django 5.2.3 on 2025-06-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_complaint_name_alter_complaint_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('nice', 'Nice'), ('medium', 'Medium'), ('bad', 'Bad')], max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
