# Generated by Django 5.2.3 on 2025-06-27 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_pollfeedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollfeedback',
            old_name='choice',
            new_name='rating',
        ),
    ]
