# Generated by Django 5.2.3 on 2025-06-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_choice_pollfeedback_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyProgressReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='mpr_reports/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
