# Generated by Django 5.2.3 on 2025-06-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_monthlyprogressreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=255)),
                ('title', models.TextField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], max_length=10)),
                ('date', models.CharField(blank=True, max_length=255)),
                ('pdf_link', models.FileField(blank=True, null=True, upload_to='internships/')),
                ('external_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
