# Generated by Django 5.2.3 on 2025-07-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='video',
            name='youtube_id',
        ),
        migrations.AddField(
            model_name='video',
            name='youtube_url',
            field=models.URLField(default='https://www.youtube.com/watch?v=dQw4w9WgXcQ', verbose_name='YouTube Video URL'),
            preserve_default=False,
        ),
    ]
