# Generated by Django 5.2.3 on 2025-07-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_contactinfo_eventitem_mediaitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media_images/'),
        ),
    ]
