# Generated by Django 5.2.3 on 2025-07-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_eventitem_image_mediaitem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('field', models.CharField(max_length=200)),
                ('image', models.URLField()),
                ('bio', models.TextField()),
            ],
        ),
    ]
