# Generated by Django 5.2.3 on 2025-07-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_boardmember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardmember',
            old_name='role',
            new_name='position',
        ),
        migrations.RemoveField(
            model_name='boardmember',
            name='bio',
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='field',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='image',
            field=models.ImageField(upload_to='board_members/'),
        ),
    ]
