# Generated by Django 5.2.3 on 2025-07-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rename_role_boardmember_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('joining_date', models.DateField()),
                ('relieving_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
