# Generated by Django 5.2.3 on 2025-07-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_staff_department_alter_staff_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='department',
        ),
        migrations.AddField(
            model_name='staff',
            name='category',
            field=models.CharField(choices=[('executive', 'Executive Leadership'), ('technical', 'Technical Team'), ('administrative', 'Administrative Staff'), ('consultant', 'Consultants & Advisors')], default='executive', max_length=20),
        ),
    ]
