# Generated by Django 5.2.3 on 2025-07-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_staff_department_staff_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='category',
            field=models.CharField(choices=[('Executive Leadership', 'Executive Leadership'), ('Technical Team', 'Technical Team'), ('Administrative Staff', 'Administrative Staff'), ('Consultants & Advisors', 'Consultants & Advisors')], default='Executive Leadership', max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.ImageField(default='staff_images/default.jpg', upload_to='staff_images/'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.CharField(max_length=100),
        ),
    ]
