# Generated by Django 5.2.3 on 2025-07-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_staff_category_alter_staff_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='category',
            field=models.CharField(choices=[('Team', 'Team'), ('Technical Team', 'Technical Team'), ('Administration Team', 'Administration Team'), ('PIU Team', 'PIU Team'), ('Site Engineers', 'Site Engineers')], default='Executive Leadership', max_length=50),
        ),
    ]
