# Generated by Django 5.2.3 on 2025-07-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Official',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='officials/')),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('priority', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
