# Generated by Django 5.2.3 on 2025-07-05 12:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_official'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='uploaded_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
