# Generated by Django 5.2.3 on 2025-07-05 14:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_tender_uploaded_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tender',
            options={'ordering': ['-last_date_to_submit']},
        ),
        migrations.RemoveField(
            model_name='tender',
            name='uploaded_on',
        ),
        migrations.AddField(
            model_name='tender',
            name='last_date_to_submit',
            field=models.DateField(default=django.utils.timezone.now, help_text='Deadline to submit the tender'),
        ),
    ]
