# Generated by Django 5.2.3 on 2025-07-05 14:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_tender_options_remove_tender_uploaded_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='last_date_to_submit',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Deadline (date & time) to submit the tender'),
        ),
    ]
