# Generated by Django 5.2.3 on 2025-07-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_tender_last_date_to_submit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='no',
            field=models.CharField(default='TEMP_NO', max_length=100),
        ),
    ]
