# Generated by Django 5.2.3 on 2025-07-05 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_tender_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tender',
            name='status',
        ),
    ]
