# Generated by Django 5.2.3 on 2025-07-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_remove_tender_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
