# Generated by Django 5.2.3 on 2025-07-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_eventitem_description_mediaitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyprogressreport',
            name='year',
            field=models.IntegerField(default=2024),
            preserve_default=False,
        ),
    ]
