# Generated by Django 5.2.3 on 2025-07-26 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_projectcategory_ongoingproject_projectimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ongoingproject',
            name='category',
        ),
    ]
