# Generated by Django 5.2.3 on 2025-07-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_remove_completedproject_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedproject',
            name='project_name',
            field=models.CharField(blank=True, default=2024, max_length=255),
            preserve_default=False,
        ),
    ]
