# Generated by Django 4.2.23 on 2025-08-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_dynamicimage_dynamicpage_delete_custompage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicpage',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='dynamic_pages/pdfs/'),
        ),
    ]
