# Generated by Django 4.2.23 on 2025-08-05 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_dynamicpage_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropdownitem',
            name='dynamic_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.dynamicpage'),
        ),
        migrations.AlterField(
            model_name='dropdownitem',
            name='href',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='dropdownitem',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
