# Generated by Django 4.2.23 on 2025-08-05 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_dropdownitem_dynamic_page_alter_dropdownitem_href_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropdownitem',
            name='href',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dropdownitem',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dropdownitem',
            name='nav_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropdown', to='api.navitem'),
        ),
        migrations.AlterField(
            model_name='dropdownitem',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
