# Generated by Django 4.2.23 on 2025-08-05 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_alter_dropdownitem_href_alter_dropdownitem_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('href', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dropdown', to='api.navigationitem')),
            ],
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='page_images/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='page_pdfs/')),
                ('message', models.TextField(blank=True)),
                ('navigation_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.navigationitem')),
            ],
        ),
        migrations.RemoveField(
            model_name='dynamicpage',
            name='images',
        ),
        migrations.RemoveField(
            model_name='navitem',
            name='dynamic_page',
        ),
        migrations.DeleteModel(
            name='DropdownItem',
        ),
        migrations.DeleteModel(
            name='DynamicImage',
        ),
        migrations.DeleteModel(
            name='DynamicPage',
        ),
        migrations.DeleteModel(
            name='NavItem',
        ),
    ]
