# Generated by Django 4.2.23 on 2025-08-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
