# Generated by Django 4.2.23 on 2025-08-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_career_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='last_date_to_apply',
            field=models.DateField(blank=True, null=True),
        ),
    ]
