# Generated by Django 4.2.23 on 2025-08-07 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_career_last_date_to_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='posted_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CareerResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Description like 'Notification', 'Apply Here', etc.", max_length=255)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='career_resources/')),
                ('link', models.URLField(blank=True, null=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='api.career')),
            ],
        ),
    ]
